server:
  port: 8080
dubbo:
  application:
    logger: slf4j
    name: yubao-live-api
    qos-enable: false
  registry:
    address: nacos://localhost:8848
    register-mode: instance
  protocol:
    name: tri
    port: 50051

spring:
  application:
    name: yubao-live-api


