server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true
    max-connections: 200
    threads:
      max: 150        # 设定处理客户请求的线程的最大数目，决定了服务器可以同时响应客户请求的数,默认200
      min-spare: 50   # 初始化线程数,最小空闲线程数,默认是10
    accept-count: 10  # 等待队列长度

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

dubbo:
  application:
    logger: slf4j
    name: yvbao-live-user-provider
  registry:
    address: nacos://192.168.88.130:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50051

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml