spring:
  config:
    name: big-market-app
  profiles:
    active: dev
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:yvbao-db-sharding.yaml


